# Generated by Django 2.2.4 on 2019-08-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=15)),
            ],
        ),
    ]
