# Generated by Django 2.2.4 on 2019-08-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['rating']},
        ),
        migrations.AddField(
            model_name='feed',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
