# Generated by Django 2.2.5 on 2019-09-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0002_auto_20190829_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('species', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-rating']},
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('value', models.IntegerField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reco.Dog')),
            ],
            options={
                'unique_together': {('date', 'dog')},
            },
        ),
    ]
