# Generated by Django 2.2.5 on 2019-09-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0003_auto_20190924_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='create_date',
        ),
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feed',
            name='price',
            field=models.CharField(max_length=30),
        ),
    ]
