# Generated by Django 2.2.5 on 2019-09-26 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0004_auto_20190926_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={},
        ),
        migrations.RemoveField(
            model_name='feed',
            name='rating',
        ),
    ]
