# Generated by Django 2.2.5 on 2019-10-10 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0005_auto_20190926_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reco.feed')),
            ],
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
