# Generated by Django 2.2.5 on 2019-10-10 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0006_auto_20191010_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='text',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
